### ISSUE TITLE
Failed to buy forged identification documents

### ISSUE THREAD

**Issue by Kasekopf** [Kasekopf/loop-casual#10]
Once every few runs, the script will fail to buy forged identification documents:
> Executing Macguffin/Buy Documents
> Desired purchase quantity not reached (wanted 1, got 0)
> Macguffin/Buy Documents not completed!
> JavaScript exception: Task Macguffin/Buy Documents did not complete within 1 attempts. Please check what went wrong. 

Just rerunning the script does not seem to help, but I am able to buy the documents manually and then continue.

**Comment by Kasekopf** [comment]
This has maybe been a bug in mafia for a long time: https://kolmafia.us/threads/bumcheekcend-ash-a-zero-setup-semi-automated-ascension-script.4963/page-269#post-142574

**Comment by MrFizzyBubbs** [comment]
Also had this happen to me after it not occurring the previous two days.

**Comment by Kasekopf** [comment]
Haven't seen this myself in 3 weeks since the most recent fix, so closing. Please reopen if it still occurs.
