### ISSUE TITLE
Bander weight is overestimated with only 1 iFlail

### ISSUE THREAD

**Issue by MrFizzyBubbs** [Kasekopf/loop-casual#18]
When executing Giant/Airship, getting the following error: `Trying to use last Bandersnatch or Stomping Boots, but weight was overestimated.`. It looks like Familiar Runaways (with offhand) assumes that the users has 2 iFlails.

**Comment by Kasekopf** [comment]
Yeah, the familiar runaway code is quite fragile with exactly what the user has available to equip. This is probably a good use case for mafia maximizer simulate=true.

**Comment by spaghetti-squash** [comment]
Post-TTT return, this may be less relevant as only peasants can afford only one iFlail.
