### ISSUE TITLE
Grey You Pull List

### ISSUE THREAD

**Issue by Kasekopf** [Kasekopf/loop-casual#19]
What pulls are useful? My KoL ascension experience is mostly in HC. Some initial thoughts for in-standard pulls:
-2 pulls for DD keys
-Smut orc keepsake box
-Blackberry Galoshes
-3 pulls for ninja climbing gear

**Comment by spaghetti-squash** [comment]
Thumb ring and carnivorous potted plant feel like no-brainers. Maybe dromedary drinking helmet if you expect to spit a lot?

**Comment by Kasekopf** [comment]
From the discord:

> sad sad gooboy brown (437479) — 02/18/2022
> very very initial pull list off the top of my head. obviously missing some stuff, just a starter list:
> 
> 11 leaf, smorc box, 3x NSA gear, loadstone, 3x dungeon gear (w/ just 2x if your wand explodes), greasy desk bell (this one i am hesitant on but i think it's a good idea if you can kill it), car battery, sinu potion, colossal mushroom, shore scrip, galoshes, lewd deck, white page (for white lion pre-whiteys for the +10% combat rate buff) or wet stew (if you don't care about the +com), surgeon gear x2, 4-d camera, pye

**Comment by spaghetti-squash** [comment]
This isn't directly related to pull list, but for grey you, because it is both a weird path and it'll be softcore even post-standard, the script should probably start using orb religiously. There are a lot of shitty little side zones we want to get a specific monster from, and orb is great for that. we can rotate through them and quest zones in order to maximize turngen. This is something that would be way easier for a script than for a player, and because we expect all or most of those to be turn-taking encounters, it shouldn't be too hard to script around the orb.

**Comment by Kasekopf** [comment]
Yeah, I agree. That was part of my motivation for the wording change from .flee to .ignore in d272fc42a2ff307b20e64c0df25a09415d297a03. The logic will be that nothing is needed by the task from ignored monsters so, if we also don't need to absorb them, they can be dodged by the orb. I plan to add orb once we get a basic grey you script working.

**Comment by Kasekopf** [comment]
I did a very haphazard 1/647 softcore run [(log)](https://github.com/Kasekopf/loop-casual/files/8145648/gyou_log_0224.txt). I didn't really plan out my pull list/YRs/camel/route, and the entire run was suboptimal in many ways. But here are what I chose in the moment.

Pulls:
```
pull: 1 dromedary drinking helmet
pull: 1 carnivorous potted plant
pull: 1 blackberry galoshes
pull: 1 antique machete
pull: 1 linoleum ore
pull: 1 Mohawk wig
pull: 1 deck of lewd playing cards
pull: 1 4-d camera (meant to be disposable instant camera... but really didn't need either)
pull: 1 beer helmet
pull: 1 distressed denim pants
pull: 1 bejeweled pledge pin
pull: 1 wet stew
pull: 1 ninja rope
pull: 1 ninja carabiner
pull: 1 ninja crampons
pull: 1 loadstone
pull: 1 time-twitching toolbelt (looks like this was pulled by the mafia maximizer, probably the same bug that people in the autoscend channel have been mentioning)
pull: 1 Boris's ring
pull: 1 Jarlsberg's earring
pull: 1 Sneaky Pete's breath spray
```

Spits:
```
149: baa-relief sheep
166: pygmy bowler
192: dairy goat
393: spiny skeleton
428: toothy sklelton
466: topiary animal
505: spiny skeleton
644: bullet bill
```

YRs:
```
59: banshee librarian
149: baa-relief sheep
225: mountain man
318: filthworm royal guard
428: toothy sklelton
505: spiny skelelton
```
