### ISSUE TITLE
Crash if we are out of hatchetfish for the fish hatchet

### ISSUE THREAD

**Issue by Pantocyclus** [Kasekopf/loop-casual#27]
Adding a ready() check to Misc/Floundry
`ready() => checkFloundry("hatchetfish"),`

after defining the following function (regex stolen from Rever)
`function checkFloundry(fish: string): boolean {	
	const sufficientFish = visitUrl("clan_viplounge.php?action=floundry").match("([0-9]+) " + fish);
	if (sufficientFish != null) return parseInt(sufficientFish[1]) >= 10;
	return false;	
}`

should suffice to resolve the issue

**Comment by Pantocyclus** [comment]
Probably not the best solution since it constantly checks the floundry each turn. Maybe a check like `step("questM05Toot") !== -1` for completion would work.

**Comment by Kasekopf** [comment]
Thanks for the regex! I added a check so that it will only check once per day (unless you change clans).
