### ISSUE TITLE
Require Pick-O-Matic lockpicks for Daily Dungeon

### ISSUE THREAD

**Issue by MrFizzyBubbs** [Kasekopf/loop-casual#28]
The "Daily Dungeon" task needs [Pick-O-Matic lockpicks](https://kol.coldfront.net/thekolwiki/index.php/Pick-O-Matic_lockpicks) for choice adventure [692](https://kol.coldfront.net/thekolwiki/index.php/I_Wanna_Be_a_Door) but it is not currently required for the task. This results in an error when encountering the choice adventure without having already have the lockpicks in your inventory. I believe adding the below line the to the task would be sufficient.

``acquire: [{ item: $item`Pick-O-Matic lockpicks` }],``

**Comment by Kasekopf** [comment]
Thanks, added!
