### ISSUE TITLE
Use Clara's Bell

### ISSUE THREAD

**Issue by Pantocyclus** [Kasekopf/loop-casual#29]
Garbo currently does not use clara's bell, so we can probably use it to force a NC. Unfortunately, if we have cartography there aren't many really good NC targets in unrestricted (island war would have been a good target without cartography, pool table may be another), especially so when we can already easily massively increase our NC%.

So far I'm thinking of the following few candidates:
Hidden Park (banish janitors to save writs?)
Hidden Hospital (could potentially save a bunch of writs, but no turnsave at all if we have writs; either way this or the hidden park seems best since it's in line with maximising profits from loops)
Cranny (ensures giant swarm)
Mosquito (guarantees we get the NC earlier than the superlikely?)

**Comment by spaghetti-squash** [comment]
It would be prudent to verify that you don't want to use the bell-charge for getting a fused fuse, ultimate mind destroyer, or NEP quest before expending the resource. Super not necessary, but would be nice.

**Comment by Kasekopf** [comment]
~~Is it worthwhile to do the NEP quest? We currently use the makeshift garbage shirt for leveling, so we can't equip the Party Hard shirt. And the rewards for the base quests don't seem that good.~~ I see; the guest passes are valuable and I should be trying to get them more often. Which NEP quests would we aim to complete with Clara's bell? The food/booze gathering ones?

I think the Hidden Apartment and Hidden Office are good candidates for the bell as well, once all the relevant items are gathered.

**Comment by Pantocyclus** [comment]
Based on the current garbo code, if we were to run loopcasual before garbo it would simply set the value of fused fuse to infinity, and would automatically choose one of the other 2 quest items to turn in for the volcoino. Saving a writ seems to almost always save more than the difference between a fused fuse (VoA) and obtaining the alternative quest items (for now, and I don't really expect the calculus to change anytime soon?).

UMD is a good call, but in this case I guess we are only using clara's bell on the casual leg? If we are simply running garbo ascend at the start of each day, then we could get the UMD on that first leg instead, so I don't really see a conflict of resources happening (unless clara's bell is used to grab something else [other than the fused fuse, which can be addressed similarly to the point above]).

**Comment by Pantocyclus** [comment]
Garbo now uses clara's bell, so we should no longer have to consider this (in the interests of meatfarming)

**Comment by spaghetti-squash** [comment]
Counterpoint: garbo only uses it for volcano and sbb; if you have access to
neither, could be worth using. Even with volcano it's inconsistent.
