### ISSUE TITLE
Tries to use Talk About Politics without Pantsgiving

### ISSUE THREAD

**Issue by pstalcup** [Kasekopf/loop-casual#3]
This happens in:
Haunted Bedroom
Daily Dungeon

**Comment by pstalcup** [comment]
This happens in

**Comment by Kasekopf** [comment]
8d7dba1 should prefer Batter Up! to Pantsgiving if available, and behave better if you don't have either.

This should fix the Bedroom issue, not sure what is going on in the Daily Dungeon.

**Comment by Kasekopf** [comment]
I was able to run through the DD today and it successfully used the malware exactly once, and killed the other monsters normally. Please reopen if you still see issues, with this or with the Bedroom.
