### ISSUE TITLE
Adv hedge for hedge maze

### ISSUE THREAD

**Issue by Imrah25** [Kasekopf/loop-casual#45]
By dumb luck I've hit the hedge maze with only a handful of adventures several times now, and it will still start the maze. Unfortunately when you run out of adventures mid maze it removes the expected choice option and it errors out due to the targeted choice option not being available. Maybe have a mandatory adventure buffer (~10 adv?) that you need before trying to tackle the tower?

**Comment by Kasekopf** [comment]
Just pushed a fix which should avoid starting the hedge maze without enough adventures to complete it. Let me know if you still run into this issue.
