### ISSUE TITLE
FR + crystal ball = crash

### ISSUE THREAD

**Issue by DamianDominoDavis** [Kasekopf/loop-casual#46]
The miniature crystal ball wants to go to FantasyRealm, and can't.

> Executing Keys/Fantasy [Route]
> Putting Sue Perdue, plicator goo the Grey Goose back into terrarium...
> You have no familiar with you.
> Possible mafia desync detected; refreshing...

**Comment by Kasekopf** [comment]
This should be fixed now, but please reopen if this is still happening.
