### ISSUE TITLE
Task Misc/Voting did not complete within 1 attempts.

### ISSUE THREAD

**Issue by JigglesTheFett** [Kasekopf/loop-casual#50]
Not sure what the issue here is, the script has been running (mostly) fine for the last few days, and anytime an error similar to this pops up I can just run the script again and it continues, but this issue is persisting.

_> loopgyou

Running loopgyou version [4977e41] in KoLmafia r26722
logPreferenceChange => true
logPreferenceChangeFilter => _lastCombatStarted,libram_savedMacro,maximizerMRUList,testudinalTeachings
Preference logPreferenceChangeFilter changed from to _lastCombatStarted,libram_savedMacro,maximizerMRUList,testudinalTeachings
Preference battleAction changed from attack with weapon to custom combat script
autoSatisfyWithMall => true
Preference autoSatisfyWithMall changed from false to true
autoSatisfyWithNPCs => true
Preference autoSatisfyWithNPCs changed from false to true
autoSatisfyWithCoinmasters => true
Preference autoSatisfyWithCoinmasters changed from false to true
dontStopForCounters => true
Preference dontStopForCounters changed from false to true
hpAutoRecoveryTarget => 0.0
Preference hpAutoRecoveryTarget changed from -0.05 to 0.0
mpAutoRecoveryTarget => 0.0
Preference mpAutoRecoveryTarget changed from -0.05 to 0.0
autoTuxedo => true
Preference autoTuxedo changed from false to true
autoPinkyRing => true
Preference autoPinkyRing changed from false to true
autoGarish => true
Preference autoGarish changed from false to true
allowNonMoodBurning => false
Preference allowNonMoodBurning changed from true to false
Preference customCombatScript changed from default to grimoire_macro
CCS set to grimoire_macro
mpAutoRecoveryItems => phonics down;knob goblin superseltzer;mountain stream soda;magical mystery juice;knob goblin seltzer;cherry cloaca cola;soda water;black cherry soda;doc galaktik's invigorating tonic
Preference mpAutoRecoveryItems changed from phonics down;knob goblin superseltzer;mountain stream soda;magical mystery juice;knob goblin seltzer;cherry cloaca cola;soda water to phonics down;knob goblin superseltzer;mountain stream soda;magical mystery juice;knob goblin seltzer;cherry cloaca cola;soda water;black cherry soda;doc galaktik's invigorating tonic
hpAutoRecoveryItems => scroll of drastic healing;cannelloni cocoon;tongue of the walrus;lasagna bandages;doc galaktik's homeopathic elixir
Preference hpAutoRecoveryItems changed from scroll of drastic healing;cannelloni cocoon;tongue of the walrus;lasagna bandages to scroll of drastic healing;cannelloni cocoon;tongue of the walrus;lasagna bandages;doc galaktik's homeopathic elixir
choiceAdventure1106 => 3
Preference choiceAdventure1106 changed from 0 to 3
choiceAdventure1107 => 1
Preference choiceAdventure1107 changed from 0 to 1
choiceAdventure1340 => 3
Preference choiceAdventure1340 changed from 0 to 3
choiceAdventure1341 => 1
Preference choiceAdventure1341 changed from 0 to 1

Executing Misc/Voting [Free action]

Executing Misc/Voting
CCS set to grimoire_macro
Autoattack is disabled.

Visiting The Voting Booth
logPreferenceChange => false
Preference logPreferenceChange changed from true to false
logPreferenceChangeFilter =>
autoSatisfyWithMall => false
autoSatisfyWithNPCs => false
autoSatisfyWithCoinmasters => false
dontStopForCounters => false
hpAutoRecoveryTarget => -0.05
mpAutoRecoveryTarget => -0.05
autoTuxedo => false
autoPinkyRing => false
autoGarish => false
allowNonMoodBurning => true
CCS set to default
(but battle action is currently set to attack with weapon)
mpAutoRecoveryItems => phonics down;knob goblin superseltzer;mountain stream soda;magical mystery juice;knob goblin seltzer;cherry cloaca cola;soda water
hpAutoRecoveryItems => scroll of drastic healing;cannelloni cocoon;tongue of the walrus;lasagna bandages
choiceAdventure1106 => 0
choiceAdventure1107 => 0
choiceAdventure1340 => 0
choiceAdventure1341 => 0
JavaScript exception: Task Misc/Voting did not complete within 1 attempts. Please check what went wrong. (file:/C:/Users/jiggl/AppData/Local/KoLmafia/scripts/loop-gyou/loopgyou.js#7378)
at file:/C:/Users/jiggl/AppData/Local/KoLmafia/scripts/loop-gyou/loopgyou.js:7378 (checkLimits)
at file:/C:/Users/jiggl/AppData/Local/KoLmafia/scripts/loop-gyou/loopgyou.js:7108 (execute)
at file:/C:/Users/jiggl/AppData/Local/KoLmafia/scripts/loop-gyou/loopgyou.js:12647 (execute)
at file:/C:/Users/jiggl/AppData/Local/KoLmafia/scripts/loop-gyou/loopgyou.js:7011 (run)
at file:/C:/Users/jiggl/AppData/Local/KoLmafia/scripts/loop-gyou/loopgyou.js:17369 (main)_

**Comment by Kasekopf** [comment]
Do you actually have the voting booth IoTM?

If you do have it, not sure what's going on. You could do the voting manually to fix it for today; once you have the I Voted sticker, the script should continue. (If you have the sticker and the script is still stuck here, try `refresh all` in the Mafia CLI).

If you don't have it, this might be a Mafia issue. You can check with `prefref voteAlways` in the CLI if Mafia thinks you have the IoTM or not. If it is mistakenly set to true, then `set voteAlways=false` should fix it.

**Comment by JigglesTheFett** [comment]
I do have the IoTM, I guess it just wasn't reading me as having the sticker properly, a refresh resolved it! Thanks!

**Comment by Kasekopf** [comment]
Well, not sure about the source of the desync. But I added the refresh as part of the script to try and workaround. Thanks!
