### ISSUE TITLE
CONSUME can fail sometimes

### ISSUE THREAD

**Issue by Pantocyclus** [Kasekopf/loop-casual#7]
CONSUME can fail if using TSP right at the cusp of level 13, causing us to delevel to 12 (and thus failing to consume items with level 13 requirements)

May require a bugfix for CONSUME, but can be circumvented by checking for myPrimestat() >= 149 instead of myLevel() >= 13

**Comment by Kasekopf** [comment]
I bumped the threshold up to primestate() >= 150 before eating starts, which should be enough for a lot of spleen consumption.
